### ISSUE TITLE
Will this project be open-sourced?

### ISSUE THREAD

**Issue by yulongg1** [robot-learning-freiburg/MDPCalib#1]
Hi, I noticed that this project has been on GitHub for a few months now, but the code hasn’t been made available yet. I’m curious if there are still plans to open-source it in the future. Thanks for your hard work!

**Comment by vniclas** [comment]
Hi @yulongg1 , thanks for your interest in our work. 

Yes! As promised, this project is still scheduled to be open-sourced upon publication. Since we received the positive news just 2 weeks ago, we are currently finalizing the release. Please stay tuned until we have resolved some open licensing questions.

**Comment by vniclas** [comment]
We released the code for coarse registration. The refinement will follow upon the public release of CMRNext.
